version: "3.9"

services:
  rabbitmq-enterpriseapp:
    image: rabbitmq:management
    container_name: "enterpriseapp-rabbitmq-local"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - enterpriseapp-network-local

networks:
  enterpriseapp-network-local:
    name: enterpriseapp-network-local
    driver: bridge