FROM nginx
COPY nginx.prod.conf /etc/nginx/nginx.conf
COPY enterpriseapp-certificate.key /etc/nginx/enterpriseapp-certificate.key
COPY enterpriseapp-certificate.pem /etc/nginx/enterpriseapp-certificate.pem